import 'dart:math';

import 'package:flutter/material.dart';
import 'package:pluto_grid/pluto_grid.dart';
import 'dart:async';
import 'package:faker/faker.dart' as fkr;

import '../../dummy_data/development.dart';
import '../../main.dart';
import '../../widget/index.dart';

part 'src/add_and_remove_column_row_screen.dart';
part 'src/add_rows_asynchronously.dart';
part 'src/cell_renderer_screen.dart';
part 'src/cell_selection_screen.dart';
part 'src/column_filtering_screen.dart';
part 'src/column_footer_screen.dart';
part 'src/column_freezing_screen.dart';
part 'src/column_group_screen.dart';
part 'src/column_hiding_screen.dart';
part 'src/column_menu_screen.dart';
part 'src/column_moving_screen.dart';
part 'src/column_resizing_screen.dart';
part 'src/column_sorting_screen.dart';
part 'src/copy_and_paste_screen.dart';
part 'src/currency_type_column_screen.dart';
part 'src/dark_mode_screen.dart';
part 'src/date_type_column_screen.dart';
part 'src/dual_mode_screen.dart';
part 'src/editing_state_screen.dart';
part 'src/export_screen.dart';
part 'src/grid_as_popup_screen.dart';
part 'src/listing_mode_screen.dart';
part 'src/moving_screen.dart';
part 'src/number_type_column_screen.dart';
part 'src/row_color_screen.dart';
part 'src/row_group_screen.dart';
part 'src/row_infinity_scroll_screen.dart';
part 'src/row_lazy_pagination_screen.dart';
part 'src/row_moving_screen.dart';
part 'src/row_pagination_screen.dart';
part 'src/row_selection_screen.dart';
part 'src/row_with_checkbox_screen.dart';
part 'src/rtl_screen.dart';
part 'src/selection_type_column_screen.dart';
part 'src/text_type_column_screen.dart';
part 'src/time_type_column_screen.dart';
part 'src/value_formatter_screen.dart';
